### ISSUE TITLE
Official community crate (?)

### ISSUE THREAD

**Issue by hecrj** [iced-rs/iced_aw#1]
Hey, iced author here! This crate is great! :tada: 

I was wondering if you would be interested in moving this crate to [the `iced-rs` organization](https://github.com/iced-rs) and make it an "official", community-driven "widget crate". We could use it to explore new widget ideas, APIs, and learn more about the current limitations. If a widget matures enough, then we could migrate it to the `iced_native` crate.

See [this Zulip discussion](https://iced.zulipchat.com/#narrow/stream/213316-general/topic/Community.20involvement.20ideas) for some context.

**Comment by Kaiden42** [comment]
Thank you very much!

This crate was developed with the ulterior motive of eventually becoming an official part of Iced. I would therefore be very happy about this idea.

**Comment by hecrj** [comment]
Awesome! I invited you to join `iced-rs`. I believe you should be able to transfer the repository there once you accept the invitation.

**Comment by Kaiden42** [comment]
Done 👍
