### ISSUE TITLE
Custom Theme for Tabs

### ISSUE THREAD

**Issue by hojjatabdollahi** [iced-rs/iced_aw#108]
Is it possible to create a custom theme for tabs?
I have been trying but it looks like there is no way to style the tabs other than with the `TabBarStyles`. 
Before I spend more time I thought to just ask here and see if it is possible at all?

**Comment by latidoremi** [comment]
All you need is something that impls the corresponding `StyleSheet`, works for almost any widget

1. Create a struct/enum
2. impl `iced_aw::style::tab_bar::StyleSheet` for the struct/enum
3. Create an instance of the struct/enum
4. Pass the instance to `TabBar::style()`

It would be better if we have a `Custom` variant tho

**Comment by hojjatabdollahi** [comment]
@latidoremi  Thank you. That's what I thought. I have done it for other widgets but not for the tabs. Would you mind taking a look at my code [here](https://github.com/hojjatabdollahi/bazaar/blob/4414d2d4319113393963293ad4ea96f6b8a5e990/src/ui/appearance.rs#L90)?
