### ISSUE TITLE
Request: File dialog, console terminal

### ISSUE THREAD

**Issue by ua-kxie** [iced-rs/iced_aw#111]
Hello, just a couple items that I think would be useful to have

File dialog: pretty self explanatory. I wasn't able to find much on how to do this in Iced.

Console terminal: equivalent to the integrated terminal in VSCode. Useful as a direct interface to bundled CLI programs.

**Comment by ua-kxie** [comment]
gotcha. Thanks for the prompt response!

unfortunately, I don't think I can implement either of these :(

**Comment by Redhawk18** [comment]
system76 actually finished this, but they never seem to contribute it to Iced.

**Comment by genusistimelord** [comment]
I'm not sure if it works for all Os's or not. as mostly they design stuff for their own Linux OS.

**Comment by Redhawk18** [comment]
> I'm not sure if it works for all Os's or not. as mostly they design stuff for their own Linux OS.

last time I talked to one of their SE's they said it would be but who knows. Hector also said he has plans of bring rfd into iced itself. and for a terminal you can use this https://github.com/Harzu/iced_term
