### ISSUE TITLE
Eye dropper for the color picker widget

### ISSUE THREAD

**Issue by bbb651** [iced-rs/iced_aw#112]
It would be nice if the color picker widget overlay showed an eye dropper.

There doesn't seem to be any cross platform eye dropper crates, I've tried to find the simplest way (that don't involve taking a screenshot and extracting one pixel from it) for each platform:
- On linux, there's a [a method for that in the Screenshot portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Screenshot.PickColor)
- On web, there's the [EyeDropper api](https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper) although it's not very well supported, currently just on desktop chromium browsers (it should also be possible to fallback to [a color input which usually includes a color picker inside it](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color))
- On windows, I found [this function](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getpixel)
- On mac, there doesn't seem to be a proper way to do it, the best I can find is [using this method to get a 1 by 1 screenshot](https://developer.apple.com/documentation/coregraphics/1454595-cgdisplaycreateimage)

These can probably live in a separate `eyedropper` crate.

The main problem I can think of is that picking a color from the screen is an inherently an asynchronous operation (will often be several seconds until the user clicks a color) and is actually an `async fn` for linux and web, and I'm not sure how that fits into a widget in iced...

**Comment by genusistimelord** [comment]
I have no idea on how this would be implemented since this indeed would have some cross platform differences. So yes there would need to be some buffer crate for this. Maybe winit has something here? but cant rely on that crate fully just in case Iced starts to support others that don't.

**Comment by genusistimelord** [comment]
I am closing this as Window would need to support this and none of them that I know of does atm for these events.
