### ISSUE TITLE
Split doesn't do scrollable operations

### ISSUE THREAD

**Issue by luizvidoto** [iced-rs/iced_aw#115]
## Description

I am facing an issue when using the Split component in conjunction with a scrollable. When executing the command to make the scrollable go to the end, it does not function as expected. However, when testing the same scrollable without the Split component, the command works properly.

## Steps to reproduce

1. Insert the Split component into the project
2. Add a scrollable inside the Split component
3. Execute the command to make the scrollable go to the end

## Expected behavior

The scrollable should go to the end when the command is executed, even when inside the Split component.

## Current behavior

The scrollable does not go to the end when inside the Split component and the command is executed.

## Environment

- Operating System: Windows 11
- Dependencies
iced = { version = "0.9.0", features = ["debug"] }
iced_aw = { version="0.5.0", features = ["split"] }
once_cell = "1.16.0"

## Additional information

- [Here is a Gist with the code I used to reproduce the bug](https://gist.github.com/luizvidoto/6f33878e3d2dfff53efaa7baf1743eb1)
- Check if the issue occurs on different browsers or operating systems, if applicable.

Please let me know if you need more information or if there is anything I can do to help diagnose and resolve the issue.

**Comment by genusistimelord** [comment]
When I finally get some time ill take a look as to why this is not working. just been super busy.....

**Comment by genusistimelord** [comment]
should be fixed in the latest main now

**Comment by luizvidoto** [comment]
Thank you very much! 👍
