### ISSUE TITLE
How to get the icon fonts like the fonts in tabs example?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [iced-rs/iced_aw#116]

**Comment by genusistimelord** [comment]
you need to download them first: https://github.com/iced-rs/iced_aw/tree/main/examples/tabs/fonts

and then load them so iced can use them. https://github.com/iced-rs/iced_aw/blob/main/examples/tabs/src/main.rs#L22

**Comment by genusistimelord** [comment]
ahh yeah I myself have no idea how to regenerate the Icon file as I have looked before to update it but was never successful myself.

**Comment by MCOfficer** [comment]
Drop it into something like fontdrop.info, you'll see that it only contains 6 glyphs. For further reading, look into "subsetting fonts" - there are tools that can shrink fonts to cover just a select number of characters. See for instance https://stackoverflow.com/a/37159128/7653274
