### ISSUE TITLE
Tabs incorrect behavior (tab bar filling widget space) when combined with window menus

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [iced-rs/iced_aw#118]
This issue is based on a [discussion thread](https://github.com/iced-rs/iced/discussions/1819). I was asked to open it.

------------

Hello

I combined the [menu](https://github.com/iced-rs/iced_aw/tree/main/examples/menu) example with the [tabs](https://github.com/iced-rs/iced_aw/tree/main/examples/tabs) example, but the result seems to be faulty somehow. The tabs bar fills the whole screen no matter what. I tried to change everything possible (even removing the icons altogether), but nothing helped. 

**Please find a minimal reproducible example in this repo**: https://github.com/TheQuantumPhysicist/IcedTabsTest

build and run with `cargo run`. On some of my machines I needed to install `libfontconfig-dev`.

Thank you and have a great day.

**Comment by TheQuantumPhysicist** [comment]
Can someone please confirm that this is a bug? I was told to put this in here but never got that confirmation.

**Comment by genusistimelord** [comment]
seems changing the view to be

pub fn view(
        &self,
        backend_controller: &NodeBackendController,
    ) -> Element<'_, Message, iced::Renderer> {
        let c = iced::widget::column![
            iced::widget::row!(self.main_menu
                .view(backend_controller)
                .map(Message::MenuMessage)),
                iced::widget::row!(self.main_widget
                .view(backend_controller)
                .map(Message::MainWidgetMessage))
        ];

        c.into()
    }
    
    fixes the issue. This might be because the Menu and other Views cant be within a column together if they are Fill or what not. Please give this a try and let me know what else might need to be looked at.

**Comment by TheQuantumPhysicist** [comment]
Yep. This fixes the issue. Thank you!

My opinion: This should be disallowed at compile-time with type-safety. There should be a class of types allowed in `column!` and `row!` that only lead to correct results.

Feel free to close this issue, or keep it open to address this problem with type-safety. Cheers!
