### ISSUE TITLE
[Feature Request] TabBar/Tabs using a type instead of `usize` for `active_tab`

### ISSUE THREAD

**Issue by andretietz** [iced-rs/iced_aw#124]
It just seems way more convinient and I couldn't find anything that speaks against this.

At the moment when a tab is clicked a function (defined in [new](https://github.com/iced-rs/iced_aw/blob/b7ed49ab2eaac314e1e2cea0435b772c0428693c/src/native/tabs.rs#L81) or [with_tabs](https://github.com/iced-rs/iced_aw/blob/b7ed49ab2eaac314e1e2cea0435b772c0428693c/src/native/tabs.rs#L97)) will be called that has an usize type for the tab that was selected. This of course works, but is quite errorprone (think of renaming or switching a tab)

I would prefer to see a Tab type, similar to `Tabs::Message`, with this developers can decide themselfes if they want to use an usize or an enum or whatever. Due to renaming or switching a tab, an enum would be way easier to handle.

**Comment by carlocorradini** [comment]
Awesome 🎉
