### ISSUE TITLE
Cannot compile TabBar example

### ISSUE THREAD

**Issue by mon** [iced-rs/iced_aw#13]
I want to build an app starting with the TabBar as a base to work off. Following the README, my cargo dependencies are:
```toml
[dependencies]
iced =  { git = "https://github.com/hecrj/iced", rev = "12c0c18d662d2b817b559b94c71d18e122c76990" }
iced_aw = { git = "https://github.com/iced-rs/iced_aw", branch = "main", default-features = false, features = ["tab_bar"] }
```

Note that I'm using `iced-rs/iced_aw` instead of `kaiden42/iced_aw` and specified the `main` branch and the `tab_bar` feature.

I then copy-pasted the source of [the TabBar example](https://github.com/iced-rs/iced_aw/blob/main/examples/tab_bar/src/main.rs) into my main.rs, but get the following errors:
```
error[E0308]: mismatched types
   --> src\main.rs:127:32
    |
127 |                     .tab_width(Length::Shrink)
    |                                ^^^^^^^^^^^^^^ expected enum `iced_core::length::Length`, found enum `Length`
    |
    = note: perhaps two different versions of crate `iced_core` are being used?

error[E0277]: the trait bound `iced_native::element::Element<'_, Message, iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend>>: From<iced_aw::native::TabBar<Message, iced_graphics::renderer::Renderer<_>>>` is not satisfied
    |
118 |             .push(
    |              ^^^^ the trait `From<iced_aw::native::TabBar<Message, iced_graphics::renderer::Renderer<_>>>` is not implemented for `iced_native::element::Element<'_, Message, iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend>>
````

I tried to solve the first by removing the `rev` from the cargo dependency, but no luck. 
The second error is totally beyond my Rust competency.

**Comment by thenlevy** [comment]
Looking at https://github.com/iced-rs/iced_aw/blob/main/Cargo.toml, I think you can simply put `iced="0.3.0" `.
If this works, you can maybe open an other issue saying that the Readme should be updated

**Comment by Kaiden42** [comment]
Yes, the readme was a bit outdated. Thank you for fixing this :slightly_frowning_face: .
