### ISSUE TITLE
number_input example doesn't work at all(Color issue?)

### ISSUE THREAD

**Issue by wiktorkujawa** [iced-rs/iced_aw#130]
It's hard for me to say, where is the problem, but it's coming from src/style/colors.rs

![number_input](https://github.com/iced-rs/iced_aw/assets/51833562/3e75c5a9-72c5-471b-922a-c10af327ff25)

**Comment by genusistimelord** [comment]
are you trying to build via WASM?

**Comment by wiktorkujawa** [comment]
yes, but it doesn't work with cargo run too.

**Comment by genusistimelord** [comment]
yeah that is because iced_aw never had the update for WASM yet. use the current main repo as that has the fix.

**Comment by genusistimelord** [comment]
@wiktorkujawa  Did you try to use the main branch yet to see if that fixed your problem?

**Comment by wiktorkujawa** [comment]
Ok, it works, but the widget is quite unstable. It loses focus all the time and changes the position of the text inside the number_ input container, I also can't directly write the float number inside this number input.

**Comment by genusistimelord** [comment]
huh? what exactly are you doing to cause it to bug out like that. as ive used it for quiet a while and had no issue with that?
