### ISSUE TITLE
Please add multi modal widget

### ISSUE THREAD

**Issue by lucatrv** [iced-rs/iced_aw#132]
The current `modal` widget is restricted to only two possible states: visible and not-visible. This makes quite tricky to implement modals with multiple possible overlays.
It would be very useful to have a `multi_modal` widget, or otherwise to extend the current `modal` widget. This widget could accept for instance a `show_modal: Option<usize>` parameter, and then an array of overlay contents. In case of `show_modal = None` no overlay would be shown, and in case of `show_modal = Some(i)` the `content[i]` overlay would be shown.

**Comment by genusistimelord** [comment]
this sounds like a decent change!

**Comment by lucatrv** [comment]
@genusistimelord please review PR #169. I think it is a better solution to support multiple overlays: it removes the `show_modal` boolean altogether and changes `overlay` into an `Option`. This way it allows maximum flexibility in choosing whether to display an overlay or not (by passing `None`). The PR is still partial (I updated only the functional code, not the comments / documentation), but would like to get your feedback on this possible approach before completing it.

Actually I think there is even a simpler solution: by removing the `Option` from `overlay` in PR #169, the user could simply show directly `underlay` (without calling `modal`) when the overlay should not be shown. This would actually be my preference, but I ask your opinion before implementing it. With this implementation, `modal` would always have the overlay visible when called.

If you do not like the two above implementations, then a new `multimodal` widget should be added accepting a `Vec` of overlays and an `usize`. If the `usize` corresponds to an element of the `Vec` of overlays, that overlay should be shown, otherwise no overlay should be shown. IMHO this is not needed though, as the above two implementations (in particular the second one) are simpler and allow maximum flexibility.

**Comment by genusistimelord** [comment]
yeah just fix the clippy issue as it should be good to merge.

**Comment by lucatrv** [comment]
Hi @genusistimelord I saw that you already merged PR #169 and fixed the clippy issue yourself. Sorry I did not answer before but yes I am also adding a multiple modals example, just hold on and I am going to PR it.

**Comment by genusistimelord** [comment]
ok thats fine. PR whenever your ready. I will close this since the last one fixed the problem.
