### ISSUE TITLE
Extend modal with right click and display it where is clicked

### ISSUE THREAD

**Issue by wiiznokes** [iced-rs/iced_aw#133]
It would be nice to have a widget to do actions with the right click of the mouse.

I think the `menu` widget could serve as a good basis for the implementation, because apart from `MenuBar`, we can use `MenuTree` I think. It would also be necessary to add the detection of the right click.

I will be happy to implement it if I can have some advice :)

**Comment by genusistimelord** [comment]
probably could implement this for modal. the only downside is we also need to keep track of mouse movement and if its within the mouse or not to allow auto closing of it.

**Comment by wiiznokes** [comment]
I'm not sure if modal is suitable.
I meant something like this: 
![Capture d’écran du 2023-06-08 00-49-50](https://github.com/iced-rs/iced_aw/assets/78230769/c393e6e8-9d3a-4e38-add3-4e738e892952)

**Comment by genusistimelord** [comment]
that would be a modal that's activated on right click basically. modal render on top when they are shown. So we can use the modal to make the ability to make right clickable screen actions. we might even be able to render it to the spot we click as well if iced allows this yet.

**Comment by wiiznokes** [comment]
Ok this seems simpler than using `menu`.
> we might even be able to render it to the spot we click as well if iced allows this yet.

the `menu` and `picklist` have this behavior I think, why iced would not allow that ?

```
fn mouse_interaction(
        &self,
        state: &Tree,
        layout: Layout<'_>,
        cursor_position: Point,
        viewport: &Rectangle,
        renderer: &Renderer,
    ) -> mouse::Interaction {
        self.underlay.as_widget().mouse_interaction(
            &state.children[0],
            layout,
            cursor_position,
            viewport,
            renderer,
        )
    }
```
I see there is no filtering in the `mouse_interaction` function of modal. So is the right click disable by default ? because only the left click work for opening it.

**Comment by genusistimelord** [comment]
the current modal uses a underlay to open the modal itself. So we would just need to make a new modal that can interact with right click. But the concepts you need to do this are in modal.

**Comment by wiiznokes** [comment]
Ok I think I get it, I just have to modify `mouse_interaction` to catch a right_click, if not, I call `underlay.mouse_interaction`.
And also find a way to display the overlay in the right place.

I think the new function will look like this: `new(underlay, overlay)`

For the state, I think it must be managed inside the widget, unlike the modal.

I do not understand the usefulness of the struct `State`?

```
#[derive(Debug, Default)]
pub struct State<S> {
    /// The visibility of the [`Modal`](Modal) overlay.
    show: bool,
    /// The state of the content of the [`Modal`](Modal) overlay.
    state: S,
}

impl<S> State<S> {
    /// Creates a new [`State`](State) containing the given state data.
    pub const fn new(s: S) -> Self {
        Self {
            show: false,
            state: s,
        }
    }

    /// Setting this to true shows the modal (the modal is open), false means
    /// the modal is hidden (closed).
    pub fn show(&mut self, b: bool) {
        self.show = b;
    }

    /// See if this modal will be shown or not.
    pub const fn is_shown(&self) -> bool {
        self.show
    }

    /// Get a mutable reference to the inner state data.
    pub fn inner_mut(&mut self) -> &mut S {
        &mut self.state
    }

    /// Get a reference to the inner state data.
    pub const fn inner(&self) -> &S {
        &self.state
    }
}
```
How to remember the state of a widget like `show_context_menu: bool` ?

**Comment by genusistimelord** [comment]
state is used to save across rendering calls. it is the only part that persists across layout and rendering. everything else is create on the spot. Some things need to persist in order for widgets to function correctly.

**Comment by wiiznokes** [comment]
yes but I don't see where is being use / initialize in `modal` ?

**Comment by wiiznokes** [comment]
I just saw in color_picker that is being initialized in impl of Widget, I will go on that i think

**Comment by wiiznokes** [comment]
well, i'm sorry but i'm really bloked on this. i have this


```
fn state(&self) -> tree::State {
        tree::State::new(State::new(false))
}
```


```
fn overlay<'b>(
        &'b mut self,
        state: &'b mut Tree,
        layout: Layout<'_>,
        renderer: &Renderer,
    ) -> Option<iced_native::overlay::Element<'b, Message, Renderer>> {
        
        let s: &mut State<bool> = state.state.downcast_mut();
        ...
}
```

and this give me this error:

```
thread 'main' panicked at 'Downcast on stateless state', /home/lenaic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/tree.rs:172:28
```

any thought ?
