### ISSUE TITLE
Modal on_event

### ISSUE THREAD

**Issue by ua-kxie** [iced-rs/iced_aw#156]
I think it may make more sense to allow users to handle events themselves, instead of accommodating specific cases like on_esc or backdrop click.

I imagine a common use case will be require it to block the backdrop content from processing events, which it currently doesnt support.

related to #133

**Comment by genusistimelord** [comment]
I agree on the events. These should be passed through to the internals.

**Comment by genusistimelord** [comment]
hmm looking at the event handlers for this Modal if they are set to None does not handle them and passes them onto the Contents events. The only difference here is you are not making the backdrop and it is centering it for you.  The only way to change this is to force you the user to position the Element where you want it to be put. 

Also #133 is a totally different issue which getting the events and passing them to all other children While also handling a Overlay for the right click menu would require a way different approach. But it is similar to how modal works. That is why I pointed him towards looking at modal to help design it.

Also the backdrop content is easy enough to make it not process events when the modal is opened. I just need to update it with a new bool to support that.

**Comment by ua-kxie** [comment]
I don't think I understood the limitations you've described - does changing how events are handled require users to deal with element positioning as well?

I guess there's the modal, the backdrop, and its contents. I think how it should work is that when modal is shown, all events should be sent to contents, before optionally being sent to the backdrop. 

`on_esc` can be user implemented by catching the event in the modal content. `backdrop` method may be dropped as well if when passing on the event to the modal content, the bounds of the modal content is passed along as well, kinda like the `update` method for canvas? Maybe in this way the user can implement for themselves too if they want to pass events along to the backdrop.

seems I didn't read #133 carefully haha

**Comment by genusistimelord** [comment]
So for Events I can either Have them or not have them at all. In which case the widget must control these events as there is no way for the people to control them externally. Also if i removed said events and you wanted to Do them manually you basically would need to remake the entire modal widget to do so. As you will have to control the positioning etc. We offer this as a Basic Base modal and as an example to help people make their own Custom ones too.
