### ISSUE TITLE
Iced_new menu widget bounds weird.

### ISSUE THREAD

**Issue by genusistimelord** [iced-rs/iced_aw#157]
Menu widgets are converted But the bounds are all wrong for somethings. Could you please take a look at this @latidoremi

**Comment by latidoremi** [comment]
Can I have a code example and screenshots? I just git pulled iced and iced_aw, the menu example seems to work fine. Btw I'm a bit tied up atm, probably won't be able to fix it rn, but will be back in a few days

**Comment by genusistimelord** [comment]
this is in compliance with #158 on what I said in the last comment.
