### ISSUE TITLE
Bug in arrow icons number input !!

### ISSUE THREAD

**Issue by amirhossein-fzl** [iced-rs/iced_aw#166]
iced version: 0.10.0
iced_aw version: 0.6.0
rust version: 1.70.0

![image](https://github.com/iced-rs/iced_aw/assets/53816722/e6b9ff1e-7119-44a4-a2c7-87420a622e81)

Please add more styling to number_input. Features such as changing arrow icons according to the icon package used in the application. Also, the ability to style arrow buttons.

If you need more information, tell me to write. This is the code I used in this application:

```rust
NumberInput::new(self.length, 50, Message::ChangeLength).style(NumberInputStyles::Default)
```

It is also appreciated that you solved the oversize problem and thanks ❤️🙏

**Comment by Redhawk18** [comment]
look at this 
https://docs.rs/iced_aw/latest/iced_aw/style/number_input/trait.StyleSheet.html

**Comment by genusistimelord** [comment]
yeah the styling will work with that stylesheet. The arrows bugging out atm i don't know what the cause would be yet. We are still working out also trying to fix other bugs with text in iced itself.

**Comment by amirhossein-fzl** [comment]
> look at this https://docs.rs/iced_aw/latest/iced_aw/style/number_input/trait.StyleSheet.html

How can I set the radius of the button? This reference you sent shows button styling in different actions.

**Comment by genusistimelord** [comment]
we would need to add that to the stylesheet. if that is what you are looking for.  Also the reason the Icon is not correct for the Number input is due to you not having the Iced_aw font loaded. , you either need to Add it to your Font repo or include it like the Example.

**Comment by genusistimelord** [comment]
where you able to get this to work?

**Comment by amirhossein-fzl** [comment]
> where you able to get this to work?

I do not understand! I didn't even try to load the iced_aw font. Naturally, this should be done by default by the library. Or that the developer (library user) is responsible for setting the icon

**Comment by genusistimelord** [comment]
we can no longer do it automatically for you. 

You either 
A:) need to load it like we did in the Example.
B:) install it into the users font folder.

either of these would fix the problem. Iced no longer has the ability to auto load these for us anymore since the new font upgrade.
We simplify the process for you by including a quick and easy way to load it in. We do not yet support custom Icons for the widgets due to many other issue's like unsupported fonts etc.

**Comment by genusistimelord** [comment]
we no longer can preload fonts in iced so it is up to the end user to ensure that are loading the required icon files for these to appear correctly. This issue is now being closed.
