### ISSUE TITLE
Add a TextArea widget

### ISSUE THREAD

**Issue by Luni-4** [iced-rs/iced_aw#17]
It would be nice to implement a `TextArea` widget for great blocks of text that might be hardly handled through an `InputText` widget. 

Something like this could be a visual example: 

![immagine](https://user-images.githubusercontent.com/12353765/117875455-7ad29800-b2a2-11eb-831e-b8f23447ba2e.png)

**Comment by Kaiden42** [comment]
This topic has come up many times ([iced#839](https://github.com/hecrj/iced/issues/839), [iced#320](https://github.com/hecrj/iced/issues/320) & [iced#197](https://github.com/hecrj/iced/issues/197)). 

Multi-line text input is really really hard to implement. Nevertheless, to be able to implement such a widget, the current text rendering approach needs a rework first ([iced#33](https://github.com/hecrj/iced/issues/33)).

**Comment by Luni-4** [comment]
Oh, I didn't know about that, thanks for the resume, now it's pretty clear. :smile: 

Feel free to close this issue anytime. I would leave it open as a reminder, but no problem if it is going to be closed.

**Comment by m00nwtchr** [comment]
Assuming I don't care about font fallback and non-English text, is this really needed for multi-line input?

**Comment by kaimast** [comment]
It probably doesn't make sense to develop a widget and then having to rewrite large chunks of it when better font rendering is added.

**Comment by Rick9622092** [comment]
I want to coding a Rich Text Editor, but Text widget has no "Selection()", "Range()" methods.

**Comment by genusistimelord** [comment]
this will probably get much better once cosmic-text is added to Iced

**Comment by genusistimelord** [comment]
Cosmic Text is finally in iced since the last update. also there is a cosmic multi line text box. Which is not in iced_aw. https://github.com/pop-os/cosmic-text/tree/main/examples/editor-libcosmic/src

**Comment by max397574** [comment]
I think this should be closed now that TextEditor got merged?

**Comment by Luni-4** [comment]
I agree, thanks a lot for the reminder!
