### ISSUE TITLE
File dialog

### ISSUE THREAD

**Issue by b1nhack** [iced-rs/iced_aw#172]
File dialog function is very scarce, there is no good solution, if you use rfd and other crates will cause the program to crash.
too hard :(

**Comment by genusistimelord** [comment]
I am confused how is this a issue for iced_aw?

**Comment by b1nhack** [comment]
No, what I mean is that there is a lack of available File dialog functionality, rfd causes crashes, there is no other solution, request someone to add File dialog functionality to iced_aw.

**Comment by genusistimelord** [comment]
you mean there is no File Dialog widget. I would wait for Iced to add that OR attempt to add it yourself as file dialog is not a fun thing to work with. Since we need to support multiple Operating systems.
