### ISSUE TITLE
Close window icon not shown correctly on modal card overlays

### ISSUE THREAD

**Issue by lucatrv** [iced-rs/iced_aw#175]
@genusistimelord please check PR#174: the close window icons of the modal card overlays that open when you click on a button are not shown correctly.

**Comment by genusistimelord** [comment]
so this is occurring because you did not load the icon font. most of the widgets need this font to run and due to this iced_aw can not be used in Sandbox mode anymore due to the latest iced changes.

https://github.com/iced-rs/iced_aw/blob/main/examples/modal/src/main.rs#L50

**Comment by lucatrv** [comment]
So do I need to turn it into an `Application`?

**Comment by genusistimelord** [comment]
yes

**Comment by lucatrv** [comment]
Couldn't the fonts be loaded behind the scenes by `iced_aw` automatically?

**Comment by genusistimelord** [comment]
no we no longer can do that since the latest Font changes. So unless hector finds a way to do this we just have to do this manually till then. @hecrj  adding you for reference to this. maybe have some sort of 3rd party library loader to load presets on iced initiation?

**Comment by genusistimelord** [comment]
fonts can not be loaded by iced_aw but we do supply the font bytes and fonts to use with our widgets. Please review all the newest examples as they show how to load iced_aw's fonts.
