### ISSUE TITLE
icons in tabbar's `IconText` Arent rendered correctly

### ISSUE THREAD

**Issue by Redhawk18** [iced-rs/iced_aw#181]
Using the Icon feature flag

```rs
tab_bar.push(i, TabLabel::IconText(icon_to_char(Icon::Alarm), String::from(filename)));
```

![image](https://github.com/iced-rs/iced_aw/assets/77415970/bb960ac1-485f-4a3b-9719-4b69c57de2f6)

**Comment by Redhawk18** [comment]
this also affects `TabLabel::Icon`

**Comment by ripytide** [comment]
I did a git-bisect on the `tabs` examples since even that seems to have got the issue now.
Looks like one of ebb9918cb78af914a19ae332e4e978c8e39abdd0 a1582a2ee60315ae5b513b1a815efe70dc1daf19 1cf5d2d30c5c7ee901bae0bab81a52c546393eea introduced the issue.

**Comment by Redhawk18** [comment]
> I did a git-bisect on the `tabs` examples since even that seems to have got the issue now. Looks like one of [ebb9918](https://github.com/iced-rs/iced_aw/commit/ebb9918cb78af914a19ae332e4e978c8e39abdd0) [a1582a2](https://github.com/iced-rs/iced_aw/commit/a1582a2ee60315ae5b513b1a815efe70dc1daf19) [1cf5d2d](https://github.com/iced-rs/iced_aw/commit/1cf5d2d30c5c7ee901bae0bab81a52c546393eea) introduced the issue.

You can observe this problem since at least 
version 0.6
![image](https://github.com/iced-rs/iced_aw/assets/77415970/892fb3ed-57f0-41d1-8515-4c62faec6d24)

version 0.7
![image](https://github.com/iced-rs/iced_aw/assets/77415970/70992fb9-4464-4e67-82da-119e76a425d5)

master
![image](https://github.com/iced-rs/iced_aw/assets/77415970/6814852d-c7d3-42f6-8412-8a6d521fbf8f)

**Comment by genusistimelord** [comment]
this should be fixed now. If @Redhawk18  could double check this one would be great!
