### ISSUE TITLE
`Picker` widget

### ISSUE THREAD

**Issue by max397574** [iced-rs/iced_aw#194]
It would be really cool to have a picker widget where you can use an input to pick items from a list.

My idea for the different data types are `items: Vec<T>`, `on_select: Box<dyn Fn(T) -> Message>`, `should_include: Box<dyn Fn(T, String) -> bool>`
So you pass the items and two closures. One of the closures gets executed when an items is selected and the other one gets called with the current input and for all the items to determine, whether the item should be sorted out or not.

Additionally it would be really cool, if the whole thing would also be controllable with keybindings (arrows and return are the obvious choices ig)

**Comment by max397574** [comment]
`combo_box` is quite similar but I was thinking about something even more general

**Comment by tseli0s** [comment]
https://github.com/iced-rs/iced_aw/

`SelectionList` is what you're looking for.

**Comment by max397574** [comment]
no absolutely not

**Comment by genusistimelord** [comment]
I dont really quite understand it either. what is this input you are looking for maybe like a Searchable SelectionList?

**Comment by genusistimelord** [comment]
closing this issue due to not enough context. can be reopened later if the poster can give a better example of this.
