### ISSUE TITLE
Beta Update to latest Iced Master

### ISSUE THREAD

**Issue by genusistimelord** [iced-rs/iced_aw#196]
Currently I have updated everything to the current except for Menu. @latidoremi could you please work on updating this to the latest master branch for me? as it might require some major changes to make it work due to how hector changed Tree.

**Comment by latidoremi** [comment]
Sorry I didn't notice the email, is the widget still working? I'll take a look at it tomorrow

**Comment by genusistimelord** [comment]
currently atm it is not. You can view all the new changes in the other widgets but the menu widget was so massive i didnt know where to start since the layout stuff will need to be redone somehow.

**Comment by jackpot51** [comment]
I have a lot of menu fixes in libcosmic. It is based on a different iced version but should be possible to backport

**Comment by latidoremi** [comment]
Man...the new changes really break a hell lot of stuff, I need to rethink a bit about the layout and how to properly sync the state tree and the menu tree, the fixes in libcosmic looks good, I'll port it here if I can't come up with something better

**Comment by jackpot51** [comment]
Majority of what I did was just to sync the tree, there were bugs with alignment before.

**Comment by justDeeevin** [comment]
Status on this?

**Comment by genusistimelord** [comment]
Teladorer is currently working on completing the last parts that we can of iced_aw before we can release.

**Comment by rizzen-yazston** [comment]
Busy making changes to make master to depend only on `iced` 0.12.0, instead of `iced_widget` as `iced` 0.12.0 does expose `canvas` as a feature.

It is a hell lot of files to update. Before tackling the `menu` feature, and look at another alignment issue somewhere.

**Comment by rizzen-yazston** [comment]
Well first commit has been merged with `main` branch, which changed the dependency from `iced_widget` to `iced` 0.12.0. Most features on `main` branch should be working with `iced` 0.12.0. A few examples has issues, and 2 examples are related to a bug found today in `iced` 0.12.0.

The `menu` feature is not ready to work with `iced` 0.12.0, and may require a rewrite. This is my next task to tackle.

**Comment by latidoremi** [comment]
I've already rewritten the menu widget, got most of the features working, still need a few more days to complete, btw what's the alignment issue? I did notice that some widgets aren't properly clipped when being scrolled to the top, I'm working on it

**Comment by genusistimelord** [comment]
mostly a issue with Grid. Where if you set the alignment to Center or Right it will overflow Glyphon. Hector said its due to infinite positioning or size or something.
