### ISSUE TITLE
run time_picker example "use_24h" don't work

### ISSUE THREAD

**Issue by zzn26** [iced-rs/iced_aw#199]
I ran the time_picker example code, but found that the "use_24h" method didn't work properly.
```
cargo.toml
iced = { version="0.10.0", features = ["tokio"] }
iced_aw = { version = "0.7.0", default-features = false, features = ["date_picker", "time_picker"] }
```
![image](https://github.com/iced-rs/iced_aw/assets/150311990/1509eb6d-a568-4865-881c-f33a3f0aa38a)

**Comment by genusistimelord** [comment]
should be fixed in the current main branch now
