### ISSUE TITLE
Tabs Closing icon

### ISSUE THREAD

**Issue by EmmanuelDodoo** [iced-rs/iced_aw#202]
I was experimenting with the `Tabs` widget and realized the closing icon for tabs as shown in the examples is not rendered properly. It seems like the specified font cannot be found. This is what is rendered in its place:
![image](https://github.com/iced-rs/iced_aw/assets/105129089/b2ec3b8e-7cea-4679-8a8d-4c81aa6e7d1a)

Zoomed in;
![Screenshot 2024-02-13 143641 zoomed](https://github.com/iced-rs/iced_aw/assets/105129089/538da72c-e9fd-46f1-887b-eea1d4f3bcab)

This is all after providing an `on_close` callback to Tabs.

I was curious and run the `TabBar` example as well and that rendered the close icon correctly.
![Screenshot 2024-02-13 143929](https://github.com/iced-rs/iced_aw/assets/105129089/e2618eb3-3954-4eb2-a154-5d904250bd1c)

Zoomed in:
![Screenshot 2024-02-13 143929 zoomed](https://github.com/iced-rs/iced_aw/assets/105129089/377b34dd-9d91-4a9a-90d2-271899cd6174)

Meaning the issue probably lies with `Tabs`. 

I have also tried going through the `Widget` implementations for both of these but as far as I can tell, everything looks in order.

All this was on a Windows 11 machine though trying on my Debian WSL2 didn't make a difference.

**Comment by genusistimelord** [comment]
the reason one works over the other is they use a specific Font.

font::load(iced_aw::graphics::icons::BOOTSTRAP_FONT_BYTES).map(Message::FontLoaded)

by adding this on the command load like shown in the tab bar example this will make them render correctly

**Comment by EmmanuelDodoo** [comment]
Yep. That solved it
