### ISSUE TITLE
Tabs causes overflow and/or overlap

### ISSUE THREAD

**Issue by Strosel** [iced-rs/iced_aw#207]
I'm currently migrating to `iced` 0.12 and therefore using the main branch of `iced_aw` and noticed that the contents of my app seem to overflow the window. After some debugging I've concluded that the issue is caused by the `Tabs` widget not properly removing the space occupied by the tab bar when allocating space for its contents. This is easily shown by changing the font size of the tab bar. Similarly if the tab bar is on the bottom of the application the contents overflow on top of the tab bar itself.

It's not really a "minimal" example but the bug is clearly visible in my application found at https://github.com/Smalands-Nation/register-rs/tree/iced-0.12.0

I can also share the following screenshots, hope it helps
<img width="736" alt="image" src="https://github.com/iced-rs/iced_aw/assets/18191699/f20daeb2-4303-4747-9c71-0b7407d0dc90">
<img width="736" alt="image" src="https://github.com/iced-rs/iced_aw/assets/18191699/5f684f9f-b303-45f0-a97a-13affc9bd792">

**Comment by genusistimelord** [comment]
I have pushed a Fix for this. If you could please give it and try and let me know if this works for your stuff!

**Comment by Strosel** [comment]
The updated version works as expected, thank you
