### ISSUE TITLE
feature request for menu - mac support

### ISSUE THREAD

**Issue by pm100** [iced-rs/iced_aw#211]
mac has a very specific way of doing menus. Would be nice if iced supported it. fltk-rs has sys-menu-bar which does the real menu bar on macos, and the classic , in app, menu bar on other platforms

I am not a mac guru so can't really offer a solution

**Comment by genusistimelord** [comment]
we can not support OS based menu's in iced_aw. if you need that, acquire about it on iced.  we only support our widget based menu here. which should for work mac etc. But it is not our goal here to support OS based features.
