### ISSUE TITLE
A way to disable on scroll behavior in number_input

### ISSUE THREAD

**Issue by Exidex** [iced-rs/iced_aw#223]
If you have a number input in scrollable() area and you scroll when your mouse just happened to be on top of the input you will accidentally change the value of input which is not desirable. So I ask for a boolean property on NumberInput to disable on scroll function. 

I also would argue that no on scroll behavior should be the default.

**Comment by Redhawk18** [comment]
Sounds like a easy first pr

**Comment by Exidex** [comment]
Resolved by https://github.com/iced-rs/iced_aw/pull/239
