### ISSUE TITLE
Card close_size extends down right when made larger

### ISSUE THREAD

**Issue by ray-5050** [iced-rs/iced_aw#225]
Using the card example, I set the close size to 30 and see that it doesn't stay centered but enlarges toward the bottom right.  When you make the width of the card smaller so that the scrollbar shows, it gets cut off.  Try size 30 or greater.  I attached a picture.  Also when the scrollbar is present, it's a bit close, maybe you could add a padding option for the whole card too.  Thanks for your help.

![card_close_size](https://github.com/iced-rs/iced_aw/assets/5865038/94932460-ea68-4638-8e19-3bfe42fcbed4)

**Comment by genusistimelord** [comment]
feel free to make a PR adding those changes to the widget. I will accept it.

**Comment by icedpygui** [comment]
Ok, it'll probably be a couple of weeks before I get to it.  Thanks.
