### ISSUE TITLE
Numberinput requires mouse hover for keyboard input

### ISSUE THREAD

**Issue by the-marenga** [iced-rs/iced_aw#232]
I got a [bug report](https://github.com/the-marenga/sf-scrapbook-helper/issues/67), that the number inputs in my application do not work.
The issue seems to be, that numberinput requires the mouse to be above the widget, even if the number inside is currently selected (blinking cursor) in order to accept keyboard inputs. This is not intuitive and not how the regular text_input behaves, which leads to users thinking they only work via the arrows. 

To make sure this is not a bug in my code, I ran the number_input example in this repo from the main branch and the issue is there as well.

My questions now are:
Is this a bug, or the desired behaviour? 
Did I miss any option to toggle this behaviour?
Am I doing something wrong?

**Comment by the-marenga** [comment]
Looking at the source, this seems to be because:
https://github.com/iced-rs/iced_aw/blob/bb7540ff017c18dc1092d7aa11b9106822a9b42b/src/widgets/number_input.rs#L409-L411
is not met, which ignores all inputs.

My question then becomes, why would this check be necessary for keyboard inputs? 
Mouse stuff might be a different story, but keyboard events check, if the input is focused themself anyways.
https://github.com/iced-rs/iced_aw/blob/bb7540ff017c18dc1092d7aa11b9106822a9b42b/src/widgets/number_input.rs#L442-L445
 
Changing the initial check to:
```Rust
        if layout
            .bounds()
            .contains(cursor.position().unwrap_or_default()) 
             || matches!(event, Event::Keyboard(keyboard::Event::KeyPressed { .. }))
``` 
Makes the widget behave as I would expect

**Comment by genusistimelord** [comment]
make sure to try that with multiple number inputs and see if they all input when the keyboard is pressed. Also yeah ill need to check to see what iced currently is doing for textboxes as this was a widget made back before many of the major changes occurred.

**Comment by the-marenga** [comment]
Just tested this with multiple number_inputs with this fix and they all behave as expected. Completely independent. They behave exactly like multiple text_inputs on switching/losing focus, whilst inputing text. 

The only thing to note is that this now allows scrolling one element, whilst inputing text into another, but I am pretty sure this is how it would be expected to behave. 

This quick fix does however call `self.content.on_event` for each unfocused number_input, whenever a key is pressed, instead of returning `event::Status::Ignored`, which might introduce something I am not aware of rn, or lead to slower perf.
In addition the keyboard input does not work, when the mouse is over the inc/dec buttons, as that logic supercedes the keyboard input checks. 

If you want, I can make a PR, that fixes this in a more sophisticated way

**Comment by genusistimelord** [comment]
please feel free too. yeah we did not want to cause weird bugs if you used the buttons over the keyboard input.
