### ISSUE TITLE
Is there anyway to move add margins around a modal's overlay? 

### ISSUE THREAD

**Issue by Bilkin-V** [iced-rs/iced_aw#238]
I want to create a modal aligned to the left and bottom. However, I wish for a little padding between it and the borders of the application window. How can I achieve this?

**Comment by genusistimelord** [comment]
there currently is no way to do that without modifying the modal struct to add in new features.

**Comment by Bilkin-V** [comment]
Ok thanks for your help

**Comment by genusistimelord** [comment]
just FYI modal and floating element will be depreciated for iced 0.14 as Stack inside Iced allows for more custom Widgets and Floating Elements.
