### ISSUE TITLE
Dependabot update to 0.9.1 fails

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [iced-rs/iced_aw#240]
Dependabot in my GH CI has attempted to update iced_aw to 0.9.1

There appears to only be a 0.9.0 release here on GH.

Crates has a 0.9.1 obviously (https://crates.io/crates/iced_aw) 

README only mentions 0.8.0 (https://github.com/iced-rs/iced_aw)

Failure to build related to bootstrap module can be seen here:
https://github.com/andrewdavidmackenzie/flow/actions/runs/8997579956/job/24715990236?pr=2219

Dependency on iced in HEAD of master is 0.12.1 (version = "0.12.1") the same as I am using in my project.

So, seems like something is out of alignment?

Any suggestions, or just hold off until a new release in crates.io?

**Comment by andrewdavidmackenzie** [comment]
Still fails with 0.9.2:

https://github.com/andrewdavidmackenzie/flow/actions/runs/9001918848/job/24729125684?pr=2222

See Cargo.toml contents here:

https://github.com/andrewdavidmackenzie/flow/pull/2222/files#diff-8a6d293dbd7f6b54e28c3f5d573ca2bc6ca4bec14ad29b92ee3714eff919b145R71

**Comment by genusistimelord** [comment]
oops, i made the card example not use icons as a feature. Also i renamed required to bootstrap via path compile when feature is not icons. sorry about that.

**Comment by genusistimelord** [comment]
so Ima take it this issue is resolved now?

**Comment by andrewdavidmackenzie** [comment]
Yes with last release
