### ISSUE TITLE
color_picker、date_picker  cannot show  button icon

### ISSUE THREAD

**Issue by rongjv** [iced-rs/iced_aw#243]

**Comment by rongjv** [comment]
![屏幕截图 2024-05-20 134055](https://github.com/iced-rs/iced_aw/assets/60056273/5c7424de-5fd7-4861-a515-4f5102ba38f7)

**Comment by genusistimelord** [comment]
you must load the font like in the Examples in order for the icons to appear. If you do not load the font, they won't render properly.

**Comment by rongjv** [comment]
> you must load the font like in the Examples in order for the icons to appear. If you do not load the font, they won't render properly.

i test,and it is worked,thank you!
