### ISSUE TITLE
Performance of rust-analyzer

### ISSUE THREAD

**Issue by wiiznokes** [iced-rs/iced_aw#244]
This project is kinda long to load on my laptop. It could be solved with 2 ways:
- moving all examples out of the workspace
- make default features an empty list

Would you accept a PR that does that ?

Also, I wanted to update an specific widget to Iced master. Would you accept a PR that does it, and thus, breaking all other widgets? (in the case of compile error on disabled feature is allowed by cargo, idk) 

thanks

**Comment by genusistimelord** [comment]
I would not mind the Examples being moved into their own Handled Area's as long as the Launch.json is updated to work with those moves. 

The Defaults are a bit of a harder issue as if they are not enabled by default a lot of people will have to redo everything to ensure they include the features individually.  If you do this, we also need to add a Rust Doc addition that still uses all the features. We could add an all feature that just includes everything to help with this.

**Comment by rizzen-yazston** [comment]
i noticed doing `cargo build --workspace` consumed just over 20 GB to build the examples. perhaps make a documentation note, best to build example you want by changing into the example's directory say `examples/menu/` and run `cargo build`.

**Comment by genusistimelord** [comment]
The issue here is without the Examples analyzer and build might not catch Errors

**Comment by wiiznokes** [comment]
> i noticed doing `cargo build --workspace` consumed just over 20 GB to build the examples. perhaps make a documentation note, best to build example you want by changing into the example's directory say `examples/menu/` and run `cargo build`.

if its just for building, you can use `cargo b --example example_name`
