### ISSUE TITLE
card head_text_color doesn't seem to change color

### ISSUE THREAD

**Issue by jondavis847** [iced-rs/iced_aw#246]
I have a custom theme in iced 0.12.1. 
```rust
#[derive(Debug, Clone, Copy, Default)]
pub enum Card {
    #[default]
    Default,
    Error,
}

impl iced_aw::style::card::StyleSheet for Theme {
    type Style = Card;

    fn active(&self, style: &Self::Style) -> iced_aw::style::card::Appearance {
        match style {
            Card::Default => iced_aw::style::card::Appearance {
                background: iced::Background::Color(self.background),
                head_background: iced::Background::Color(self.node_background),
                head_text_color: self.primary,
                border_color: self.border,
                ..iced_aw::style::card::Appearance::default()
            },
            Card::Error => {
                iced_aw::style::card::Appearance {
                    background: iced::Background::Color(self.background),
                    head_background: iced::Background::Color(self.error),
                    head_text_color: self.error,
                    border_color: self.border,
                    ..iced_aw::style::card::Appearance::default()
                }
            }
        }
    }
}
```

Changing the head background color for Default and Error both work as expected. However, attempting to change head_text_color to anything doesn't seem to have any affect. In the Error code above, the head_background and head_text_color should both be self.error which is red, but the text is still white. Trying other colors also seems to not have any affect.

![image](https://github.com/iced-rs/iced_aw/assets/91633610/53841359-1849-4100-b592-d27042448cdb)

**Comment by genusistimelord** [comment]
we are currently slowly working on migrating the theme system to the latest one found in iced master. This might fix some of these issues.

**Comment by jondavis847** [comment]
Excellent thanks. Should I wait for the release to close if it's fixed?

**Comment by genusistimelord** [comment]
If you can switch over to the main branch and give it a try. That also means switching to iced main branch too. If it's fixed let me know, and we can close this, otherwise leave it open.
