### ISSUE TITLE
Why does Grid insert spaces between narrow columns to the right of a wider column? (and how to avoid)

### ISSUE THREAD

**Issue by mackler** [iced-rs/iced_aw#248]
Hi, I'm trying to learn to use `Grid` and `GridRow` for text-alignment purposes.

When I use this code, it does what I expect:

```
    fn view(&self) -> Element<Self::Message> {
        let row = GridRow::with_elements(vec![
            Text::new("x"),
            Text::new("x"),
            Text::new("x"),
            Text::new("x"),
            Text::new("longer string of text"),
        ]);

        let grid = Grid::with_rows(vec![row]).column_width(Length::Fixed(5.0));
        grid.into()
    }
```
![image](https://github.com/iced-rs/iced_aw/assets/1840214/b8a69338-bcc5-408a-acd5-88c569319579)

The cells are all together with no space between them.  But if I move the cell with wider text from the last to the first like this:
```
        let row = GridRow::with_elements(vec![
            Text::new("longer string of text"),
            Text::new("x"),
            Text::new("x"),
            Text::new("x"),
            Text::new("x"),
        ]);
```
now I get this:
![image](https://github.com/iced-rs/iced_aw/assets/1840214/068fc240-fe43-4cae-b46c-1c6003f22d60)
Now instead of the cells being together, they are spaced out.  Why?  Yes I have read the documentation but no I still don't understand the logic.  In both cases I have set the width of all columns to a fixed value of 5.  What if I want **both** the wider cell to be on the left and **also** for the cells to have no space between them?  How can I accomplish that?

(Also this is just a single-row example, my use case has multiple rows so the standard iced `Row` apparently will not meet my need for a grid.)

Thanks!

**Comment by genusistimelord** [comment]
it seems to be because inside the layout logic it is calculating a min_size like 

 min_width = if width == f32::INFINITY {
                min_width
            } else {
                min_width.max(width)
            };


if the first is the bigger width, the rest will be set to that width. I really am not sure how Grid Really should be done, or what the original author's purpose of Grid was for.
