### ISSUE TITLE
Port iced_aw to iced 0.13

### ISSUE THREAD

**Issue by cbeust** [iced-rs/iced_aw#249]
It would be helpful to have a branch of iced_aw that's ported to iced 0.13.

**Comment by genusistimelord** [comment]
ok this will be released once I am finished testing the widgets against iced 0.13's release.

**Comment by cbeust** [comment]
Not sure if I should file a separate issue for this but it's a simple question: `Tabs` doesn't seem to be convertible into an `Element` any more, am I missing something?

**Comment by genusistimelord** [comment]
you are using an older version not compatible with iced 0.13 you need to set to the correct version and then run cargo clean and cargo update. This normally fixes that issue.
