### ISSUE TITLE
Icons not properly rendered

### ISSUE THREAD

**Issue by Ultraxime** [iced-rs/iced_aw#256]
Hello,

I'm using iced_aw to use its widgets in my software.

However I encounter an issue: while using color_picker the check and the X are rendered as question marks in boxes, the same goes for the arrows in number_input.

![image](https://github.com/iced-rs/iced_aw/assets/36888699/cb763f68-7c48-42a0-8c1d-b3c1b3f3568f)
![image](https://github.com/iced-rs/iced_aw/assets/36888699/af021c1c-b903-4a48-9236-5fa146fcbd4b)

Does anyone have an idea of where it comes from ?
Maybe it's because I'm lacking the glyphs on my computer (I'm running with ArchLinux) but it seems that the glyphs are embedded in iced_aw.

Thank you for any help

**Comment by genusistimelord** [comment]
what version of iced and iced_aw?

**Comment by Ultraxime** [comment]
> what version of iced and iced_aw?
I'm using iced 0.12.1 and iced_aw 0.9.3

> Did you make sure to load the fonts into iced?
I don't know how to load the font, as it is the one you defined in iced_aw. (If I understood properly)

**Comment by genusistimelord** [comment]
https://github.com/iced-rs/iced_aw/blob/67de1be745c67564c2373b27111c3042da5d1c7f/examples/number_input/src/main.rs#L55
you need to load it like the above example. The newest iced in the main branch is much nicer than this older one. But for now you need to do it this way.

**Comment by Ultraxime** [comment]
Thank you
It solved my issue
