### ISSUE TITLE
Cross-Compatibility Issue with Menu Bar on Linux

### ISSUE THREAD

**Issue by sundaram123krishnan** [iced-rs/iced_aw#275]
So in our [pigg](https://github.com/andrewdavidmackenzie/pigg) app, we induced some custom button styles to manipulate the default behavior of button in the menu bar.
So, in the style when the default color of button and hovered color button is different then the menu bar becomes black on Linux.
But, it works perfectly fine in macOS.

In macOS,

<img width="274" alt="mac" src="https://github.com/user-attachments/assets/630cfc1f-b02a-4e3e-875b-8aeb7b94569d">

In my local machine (Arch linux),

![image](https://github.com/user-attachments/assets/8597d567-ca54-4893-b3b7-fd2f2bd435a3)

This is found in raspberry pi as well

**Comment by genusistimelord** [comment]
I actually have no idea what the cause would be

**Comment by sundaram123krishnan** [comment]
Seems to be an issue with `iced`.
Thx for ur response @genusistimelord
