### ISSUE TITLE
Tabs is not implemented From for Element

### ISSUE THREAD

**Issue by eribol** [iced-rs/iced_aw#276]
I am using iced 0.13.0-dev version with iced_aw beta version but in examples, Tabs  into() is works but with beta version it does not compile.

```
the trait bound `iced_core::element::Element<'_, Message, Theme, iced_renderer::fallback::Renderer<iced_wgpu::Renderer, iced_tiny_skia::Renderer>>: From<Tabs<'_, Message, TabId, _, _>>` is not satisfied
  --> src/main.rs:62:14
   |
62 |             .into()
   |              ^^^^ the trait `From<Tabs<'_, Message, TabId, _, _>>` is not implemented for `Element<'_, Message, Theme, Renderer<Renderer, ...>>`, which is required by `Tabs<'_, Message, TabId, _, _>: Into<_>`
```

**Comment by genusistimelord** [comment]
try the main branch

**Comment by eribol** [comment]
```
[dependencies.iced]
git = "https://github.com/iced-rs/iced.git"
branch = "master"
default-features = false
features = ["advanced","wgpu"]
[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw.git"
branch = "main"
default-features = false
features = ["tabs","icons"]
```
still gets a lot of implementation error;
[err.txt](https://github.com/user-attachments/files/16539545/err.txt)

**Comment by genusistimelord** [comment]
That error means that something is not syncing up in your library cache. You probably need to run

Cargo Clean
Cargo Update

As the example, in iced_aw, compiles and runs perfectly fine with no errors.

**Comment by eribol** [comment]
It works perfect when i clone iced-iced_aw and run cargo run -p tabs but when i create new project, copy the all tabs example in it i get tons of error.
[err.txt](https://github.com/user-attachments/files/16592017/err.txt)

**Comment by genusistimelord** [comment]
yeah this is some sort of cache issue.

**Comment by eribol** [comment]
But it does not fix. I cleaned everything but still it does not work.

**Comment by eribol** [comment]
Okey, changed iced branch master with version = "0.13.0-dev" and worked.

**Comment by eribol** [comment]
Okey, changed iced branch master with version = "0.13.0-dev" and worked.
