### ISSUE TITLE
Error with Number Input in Grid

### ISSUE THREAD

**Issue by Ultraxime** [iced-rs/iced_aw#278]
Hello,

I encountered an issue when integrating a Number Input in a Grid.
The Number Input seems to be cropped, I tried to fix the code myself but did not find its origin.

The code is the following 
```rust
let stars = NumberInput::new(self.stars, 0..=3, move |stars| {
    messaging(Message::Stars(stars))
});

Grid::with_rows(vec![
    GridRow::with_elements(vec![stars]),
])
```

and the rendering is 
![image](https://github.com/user-attachments/assets/79c3817c-b1ad-4bd2-9bc8-807f86410db0)
We can see that the value is not shown (should have been 3) and the decrease button is not here.

During these peregrinations, I also noticed that the padding was not working well.
![image](https://github.com/user-attachments/assets/8518c3f0-e5ed-4686-8015-fd12fcf9a772)
Here we can see that the padding is not the same to the left and to the right in the Card widget

I'll be happy to help

**Comment by genusistimelord** [comment]
it would be something in the Layout functions that deal with how it should be displayed.

**Comment by Ultraxime** [comment]
I guessed but I haven't figured out how it works 

Maybe I will dive in it later, but as for now I don't know how to do it

**Comment by genusistimelord** [comment]
so this should be fixed then @Ultraxime?

**Comment by Ultraxime** [comment]
Yes it should 
At least I used the same code and didn't reproduced the error
