### ISSUE TITLE
Can't edit NumberInput using keyboard

### ISSUE THREAD

**Issue by ales-tsurko** [iced-rs/iced_aw#299]
I can select the text, can move the cursor, and can add the numbers after the coma, but can't remove or edit the value further.

On the screenshot, for example, I entered a float number, by adding the dot and number after it. But then I can't remove it using the delete/backspace button.

<img width="165" alt="Screenshot 2024-10-26 at 23 50 12" src="https://github.com/user-attachments/assets/e752ade2-1ac6-4d07-87aa-e2154d80dd07">

**Comment by genusistimelord** [comment]
where you doing this from a Mac?

**Comment by ales-tsurko** [comment]
Why did you close it?

**Comment by ales-tsurko** [comment]
> you never replied back. Also I did make some changes in Main to allow entering the Decimal and - without the need for Text. I can reopen it if it is still an issue within the main branch.

Just tested it and now I can edit the number as described. But now it’s sometimes impossible to enter dot/comma. For example, if you run the example for the number input, try to enter three digit and then type dot/comma. Or sometimes it happens with a single digit. In overall, you can now edit a float after it entered, but it has issues entering it.

For your question about where I’m running it: it’s the latest macOS and the number input example.

**Comment by genusistimelord** [comment]
yeah I am trying to solve this issue right now with the enter issue. It has to do with Text Versus the Value not wanting to accept each other and keep the .

**Comment by genusistimelord** [comment]
that seems to be the one thing I can not figure out the best way to Fix ATM. the reason seems to be when the Value is converted to a String if its a 0.0 or a 1.0 it somehow becomes a 1 or 0 as it gets rid of the .0. Not sure how to Deal with this atm.
