### ISSUE TITLE
Unwrap in menu overlay causes app to crash

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [iced-rs/iced_aw#301]
In my app, some hardware events cause additions to / removals from menus asynchronously.

It seems that when that happens and the menu is open, a crash happens.

It seems to be this Option unwrap:

https://github.com/iced-rs/iced_aw/blob/main/src/widget/menu/menu_bar_overlay.rs#L90

**Comment by genusistimelord** [comment]
We may need to remove the unwrap and replace it with a full if let statement for menu. that should fix the error.

**Comment by andrewdavidmackenzie** [comment]
"Thar she blows...." https://github.com/iced-rs/iced_aw/pull/307

I fixed the 2 or 3 that were causing my particular crash, plus others I could see in the file.

To fix completely might require some restructuring of those methods.

Idea goal would be to remove the allow of unwraps at the top of the file.

If you review the PR with comments, I am willing to address those comments and get the PR into a state for merging.
