### ISSUE TITLE
numeric input cannot enter negative numbers

### ISSUE THREAD

**Issue by Adam-Ladd** [iced-rs/iced_aw#304]
Numeric input supports negative number types (e.g. i128) however, as it is not possible to enter a minus sign in the numeric input it is functionally impossible to use them. Please add support for entering a minus sign for negative numbers.

**Comment by genusistimelord** [comment]
It can add a negative sign to numbers, But you must first have a number in there before you can click and add a negative sign ATM.  Ill look into what we can do to allow typing it wholly.

**Comment by genusistimelord** [comment]
this should now work fully with the latest main. Please give it a test,
