### ISSUE TITLE
Numeric input please add support for formatting 

### ISSUE THREAD

**Issue by Adam-Ladd** [iced-rs/iced_aw#305]
Would it please be possible to add support for formatting the number in the numeric input. The motivation is as follows:

I would like enter a price. The best rust crate (to the best of my knowledge) is the rust_decimal crate. Unfortunately the decimal type cannot be used directly in the numeric input widget as it does not implement num_traits::bounded, therefore I am using an i128 value for the value in numeric input which is then converted back and forth to a decimal as required with the final two digits being used for cent's/pence/e.c.t.  therefore the number displayed in the input is actually 100x greater than the price. I would therefore like an option to format the numeric input to add a decimal point in the appropriate position. 

Thanks,

**Comment by genusistimelord** [comment]
I would ask them to implement num_traits::bounded OR ask num_traits to add a feature for rust_decimal. This is not our problem here to solve. We require Bounded because we need to support Ranges properly.

**Comment by Adam-Ladd** [comment]
Absolutely agreed and I will do (though considering the popularity of the crate I suspect there is some technical reason they can't). 

However, I'm not asking you to add support for the decimal type. What I'm asking is if it would be possible to add the ability to format the text entered. E.g. so that the user could enter 100 but I could put that input through a `format!` macro and end up with the input box showing "1.00"

**Comment by genusistimelord** [comment]
yeah this will not be possible as we can not really rely on a float being a integer and a integer being a float and not knowing which is which. This is part of the reason why its Really Strict.

**Comment by Adam-Ladd** [comment]
> yeah this will not be possible as we can not really rely on a float being a integer and a integer being a float and not knowing which is which. This is part of the reason why its Really Strict.

I thought since the number input has a known type at compile time that wouldn't be an issue but thanks all the same.

**Comment by Ultraxime** [comment]
Hi, 

A solution to your initial problem would be to create your own custom struct that is a wrapper over the decimal type.
Your struct could then implements everything that is needed for the number input.
It has to be noted that the only authorized characters to be typed are the digit (0-9), the point (`.`) and the minus sign (`-`).

If it's not enough for you I would advise you to create your own widget based on the typed_input with inspiration from the number_input.

**Comment by Adam-Ladd** [comment]
> Hi,
> 
> A solution to your initial problem would be to create your own custom struct that is a wrapper over the decimal type. Your struct could then implements everything that is needed for the number input. It has to be noted that the only authorized characters to be typed are the digit (0-9), the point (`.`) and the minus sign (`-`).
> 
> If it's not enough for you I would advise you to create your own widget based on the typed_input with inspiration from the number_input.

Thanks, I forgot that wrapper structs can implement traits that their contents do not. 

Creating my own widget would be ideal. However, unfortunately I don't currently  have the skill to do so. However, if your offer from #306 of showing me how/where to find out how is on that would be fantastic
