### ISSUE TITLE
Typed input please add support for an on invalid input

### ISSUE THREAD

**Issue by Adam-Ladd** [iced-rs/iced_aw#306]
Typed input works fantastically. However, unfortunately it is fairly easy for the user to enter invalid input without realizing, this is an especially big issue if the user previously entered valid input as the state of the program will then reflect the previous invalid input without the user realizing it. 

Given this could you please add an option for a message to be produced when the user enters invalid input. This would allow the program to notify the user of their error e.g. by changing the background of the input to red.

**Comment by Ultraxime** [comment]
Hi,
I should be able to produce a message on wrong input. But originally I designed the submit message for the developers to catch wrong input.
To perform what you are saying, changing the colour, I was thinking more of a special theme for the widget but I don't know how to do it.

**Comment by Ultraxime** [comment]
I hear you.

An issue is, if I mastered enough Iced, that once a message is emitted and treated by the update method of the application, the view method is called, recreating the widget.
That way, if I create a message for invalid input, the input will be returned but once the view method is called the previous valid value will be used instead of the one currently written by the user.
You can try it with the submit message by slightly altering the typed_input example for it to catch submit event.
This behavior is not something desirable.

I'll be happy to explain to you how to create a variant of the typed input that fit your wish but won't add the `on_invalid_input` message unless someone justify it to me.

On the other hand, once I will be more fluent with the themes, I'll more than probably create a theme for the typed input, for them to change color when the input is invalid.

I hope it helps you and I was clear enough.

**Comment by Adam-Ladd** [comment]
> I hear you.
> 
> An issue is, if I mastered enough Iced, that once a message is emitted and treated by the update method of the application, the view method is called, recreating the widget. That way, if I create a message for invalid input, the input will be returned but once the view method is called the previous valid value will be used instead of the one currently written by the user. You can try it with the submit message by slightly altering the typed_input example for it to catch submit event. This behavior is not something desirable.
> 
> I'll be happy to explain to you how to create a variant of the typed input that fit your wish but won't add the `on_invalid_input` message unless someone justify it to me.
> 
> On the other hand, once I will be more fluent with the themes, I'll more than probably create a theme for the typed input, for them to change color when the input is invalid.
> 
> I hope it helps you and I was clear enough.

Thanks that makes a lot of sense. If you'd be willing to explain to me how to create my own widget that would be fantastic. TBH from the looks of things all I want to do is take what you've currently got and replace `on_change` with `on_submit` but if you'd be willing to take me through the details and/or let me know where I can do some reading to get more familiar with the technicalities of iced that would be fantastic as I'd like to make some of my own widgets in the future (hopefully sending some PR's to this crates once I'm up to speed). 

I do think there is value in a "checked" version of typed input beyond the color change. As I'm currently using an `Option` for the state controlled by the typed input. The `Option` is set to `None` by default and then changed to a `Some` variant when valid input is entered. Unfortunately with the current form of this widget I don't have a way to turn it back to a `None` if the user then enters invalid input (unless they submit it) so I do think a variant where `on_change` returns a result has value (at least for my use case).

**Comment by Ultraxime** [comment]
To do what you want, you should :
* Add a field to the struct : `on_invalid` its type should be similar to the one `on_change` but take a `String` instead of `T`
* Create a new method to set this field, like the method `on_input`
* Then change the `if` line 350 to handle the case when `T::from_str` fails and do something similar to line 353-355

For me the keeping the previous valid value is better than destroying it when something invalid is entered. Especially since the user can be prone to typos and will be quite unhappy if everything it did is destroyed.

**Comment by Adam-Ladd** [comment]
> To do what you want, you should :
> 
>     * Add a field to the struct : `on_invalid` its type should be similar to the one `on_change` but take a `String` instead of `T`
> 
>     * Create a new method to set this field, like the method `on_input`
> 
>     * Then change the `if` line 350 to handle the case when `T::from_str` fails and do something similar to line 353-355
> 
> 
> For me the keeping the previous valid value is better than destroying it when something invalid is entered. Especially since the user can be prone to typos and will be quite unhappy if everything they did is destroyed.

Thanks, I definitely agree with keeping the user input in the box intact (destroying that is just going to be really annoying) but if they're making a typo I'd rather unset the value and wait for them to enter a valid one as in this case I'm taking a price as an input and I'd rather not have that entered incorrectly. 

As for the instructions that covers what I was originally asking for but if I'm creating my own widget I'd rather just replace `on_change` so it's message type is a `Result<T, String> (like`on_submit` currently is). As this would both valid and invalid input are handled and remove the need for an extra method. 

Would this just be a case of replacing line 121 with a duplicate of line 135 or is there anything else I would need to consider?

Btw I've already gone through the book https://book.iced.rs/additional-resources.html the pocket guide and the video guide for the text editor (updating it as I went to the latest version of iced) but I'm struggling to find anything more advanced and the documentation is fairly lacking in some places. Do you know of anything else I should check out to learn more about the framework?

**Comment by Ultraxime** [comment]
>Thanks, I definitely agree with keeping the user input in the box intact (destroying that is just going to be really annoying) but if they're making a typo I'd rather unset the value and wait for them to enter a valid one as in this case I'm taking a price as an input and I'd rather not have that entered incorrectly.

In that case you could just disable the on change and just force your user to submit their modification by using enter, that way it's safer for the user.
The typed_input still work when on change is disabled but on_submit is enabled.

> As for the instructions that covers what I was originally asking for but if I'm creating my own widget I'd rather just replace on_change so it's message type is a Result<T, String> (likeon_submit` currently is). As this would both valid and invalid input are handled and remove the need for an extra method.

For what you are doing, if you don't make a difference between valid and wrong input, you could just use a text input and perform the `T::from_str` directly in your update method.


> Would this just be a case of replacing line 121 with a duplicate of line 135 or is there anything else I would need to consider?

You would also need to update the logic line 350.


> Btw I've already gone through the book https://book.iced.rs/additional-resources.html the pocket guide and the video guide for the text editor (updating it as I went to the latest version of iced) but I'm struggling to find anything more advanced and the documentation is fairly lacking in some places. Do you know of anything else I should check out to learn more about the framework?

If I had something better I wouldn't have spent hours trying to figure how everything is working, I'm sorry.
But for my part I'll try to comment more my code to help with that.

**Comment by Adam-Ladd** [comment]
> > Thanks, I definitely agree with keeping the user input in the box intact (destroying that is just going to be really annoying) but if they're making a typo I'd rather unset the value and wait for them to enter a valid one as in this case I'm taking a price as an input and I'd rather not have that entered incorrectly.
> 
> In that case you could just disable the on change and just force your user to submit their modification by using enter, that way it's safer for the user. The typed_input still work when on change is disabled but on_submit is enabled.
> 
> > As for the instructions that covers what I was originally asking for but if I'm creating my own widget I'd rather just replace on_change so it's message type is a Result<T, String> (likeon_submit` currently is). As this would both valid and invalid input are handled and remove the need for an extra method.
> 
> For what you are doing, if you don't make a difference between valid and wrong input, you could just use a text input and perform the `T::from_str` directly in your update method.
> 
> > Would this just be a case of replacing line 121 with a duplicate of line 135 or is there anything else I would need to consider?
> 
> You would also need to update the logic line 350.
> 
> > Btw I've already gone through the book https://book.iced.rs/additional-resources.html the pocket guide and the video guide for the text editor (updating it as I went to the latest version of iced) but I'm struggling to find anything more advanced and the documentation is fairly lacking in some places. Do you know of anything else I should check out to learn more about the framework?
> 
> If I had something better I wouldn't have spent hours trying to figure how everything is working, I'm sorry. But for my part I'll try to comment more my code to help with that.

Btw I missed it before but hector (the guy who seems to have written most of iced) has been doing some streaming and there are recordings on youtube https://www.youtube.com/channel/UC3pADUw9fJBxWgxBk0QkaYQ there are also a couple of blogs in the awesome iced repo which may come in handy https://github.com/iced-rs/awesome-iced . If you'd be willing to comment your widgets that would be fab to have a look at too. Thanks again
