### ISSUE TITLE
Selection list in split (invisible/non-displaying)

### ISSUE THREAD

**Issue by barvirm** [iced-rs/iced_aw#31]
Hello, I have trouble with the selection list in a split.

https://github.com/barvirm/Radventurer

```
// self.paths = vec!["FIRST ROW IN LIST".to_string(), "SECOND ROW IN LIST".to_string()]
let first = Container::new(Text::new("First"))
    .width(Length::Fill)
    .height(Length::Fill);

let selection_list = SelectionList::new(
    &mut self.selection_state,
    &self.paths[..],
    Some(self.selected_path.clone()),
    Message::OnFileClick,
);
    
let split = Split::new(&mut self.split_pane, first, selection_list, Message::OnResize);

```

![image](https://user-images.githubusercontent.com/15948420/124187440-2091ce80-dabe-11eb-9744-1b59c30d83c6.png)

**Comment by genusistimelord** [comment]
Thank you for reporting this I will take a look to see what is happening.

**Comment by Kaiden42** [comment]
It seems that I've forgotten to implement the overlay funktion on the split widget. I can tackle this issue tomorrow. Thank you for reporting it. 🙂

**Comment by Kaiden42** [comment]
This should fix this issue. If it still persists, feel free to reopen it.

**Comment by barvirm** [comment]
Now it's just miss placed? I assume this code should move it into "second row".
```
        let first_row = Row::new()
            .spacing(0)
            .padding(0)
            .width(Length::Fill)
            .push(left_button)
            .push(right_button)
            .push(text_input);


        let shortcut_list = SelectionList::new(
            &mut self.shortcut_list,
            &Dirs::ALL,
            None,
            Message::ShortcutClick
        );

        let selection_list = Container::new(Text::new("SL")).width(Length::Fill);
        let second_row = Row::new().push(shortcut_list).push(selection_list);

        let content = Column::new().push(first_row).push(second_row);
```

![image](https://user-images.githubusercontent.com/15948420/124305457-6c4b8300-db65-11eb-9f4e-4f7509789f9f.png)

**Comment by genusistimelord** [comment]
Yeah I am working on Fixing the Selection list so it Views correctly when rendered. Currently it uses the Iced way of handling Overlay Menus. I am attempting to change it so it is more direct way of rendering.

**Comment by genusistimelord** [comment]
I have fixed the Sizing issues and placement issues with the Selection list. However in the process i have updated how it is made and works. So please see the updated Example when the Request gets Pulled. @barvirm
