### ISSUE TITLE
icon text display issue

### ISSUE THREAD

**Issue by Cupnfish** [iced-rs/iced_aw#34]
I used date_picker in my project, but those icons don't display correctly. Is the font file not configuring in Cargo.toml via git?
<img width="317" alt="截屏2021-07-02 下午11 03 13" src="https://user-images.githubusercontent.com/40173605/124293902-b5153300-db89-11eb-94ee-55acde422a80.png">

**Comment by Kaiden42** [comment]
Are you importing your own icon font? I recently had the same issue. My problem was that I have imported an other font under the same name as the icon font of iced_aw. The icons of iced_aw are named `"Icons"`. If you import an other font under the same name they infer with each other.
```Rust
pub const ICON_FONT: Font = Font::External {
    name: "Icons", // Use a different name here
    bytes: include_bytes!("../font/icons.ttf"),
};
```

**Comment by Cupnfish** [comment]
Thank you very much, it solved my problem!

**Comment by Kaiden42** [comment]
I've reopened this issue as a reminder to rename the icon font of iced_aw to something more unique in the future. A more unique name would save a headache for the next person struggling with this issue.

**Comment by bobgates** [comment]
Hi. I've got the same issue. I'm using tabbar (which uses icons) and date_picker. I'm not importing my own icons, but the date_picker has the buttons without icons as above. If I wanted to use the solution above, where do I make changes?

**Comment by Kaiden42** [comment]
If you are not importing your own icons and the icons are visible on the tabbar but not on the date_picker, this seems like a different kind of bug as there is no second icon font messing around with the one of iced_aw itself :thinking:

**Comment by mkrueger** [comment]
Thanks for leaving that open - had the same issue  :)

**Comment by genusistimelord** [comment]
this is no longer relevant on how iced uses fonts.
