### ISSUE TITLE
Tabs and TabBar on web

### ISSUE THREAD

**Issue by Icelk** [iced-rs/iced_aw#38]
Awesome project!
Do you @Kaiden42 have any plans on making the Tabs and specifically TabBar widget available on the web?

**Comment by Kaiden42** [comment]
> Awesome project!

Thanks!

I could take a look at this on the upcomming days. It wouldn't be that hard to implement. The only problem I can see so far is using the Icons as there is currently no easy way of specifying the icon font on the web AFAIK.

**Comment by Icelk** [comment]
Thanks!
