### ISSUE TITLE
Problems combing tabs and a plotters instance

### ISSUE THREAD

**Issue by bobgates** [iced-rs/iced_aw#42]
Hi

I can use `plotters-iced` to successfully put a chart into an `iced` page that also contains a slider, using the  split-chart example. I  add slider parameters to the `Message` and the `State` structs, then add a `.push(self.chart.view())` to the view code and it works as expected.

However, if I try the same thing using the tabs example code from iced_aw, where there isn't a `view` method, but rather a 'content' method, if I add `.push(self.chart.view())` I end up with an error:

```
.push(self.chart.view());
   |              ^^^^ the trait `From<iced_native::element::Element<'_, Message, iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend>>>` is not implemented for `iced_native::element::Element<'_, TimePlotMessage, iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend>>`
```

In this case, I'm replacing the ```ferris``` jpeg in the ```iced_aw``` example ```tabs``` with the call to the ```plotters-iced``` chart. I'm stumped. I'm pretty sure this is my fault, but in the meanwhile, can anyone point me in the right direction? Until then, back to an app without a tab bar.

**Comment by Kaiden42** [comment]
Based on the error message, I assume you have a problem with the message types. It expects an `Element<Message>` but you are pushing an `Element<TimePlotMessage>`. The `Message` type of the container, you are pushing your plot to, is from type `FerrisMessage` not `TimePlotMessage` (If replacing the adding of the ferris image with the plot is the only thing you have changed). The tabs example contains of different message types for each part in the application. These types build a hierarchically structure. You have to wrap your message to the higher message type once your message is bubbling up the structure.

You could add a variant like `Plot(TimePlotMessage)` to the `FerrisMessage` enum like this:
```Rust
#[derive(Debug, Clone)]
pub enum FerrisMessage {
    ImageWidthChanged(u16),
    Plot(TimePlotMessage),
}
```
Than wrap the message the plot produces in a `FerrisMessage` with the `map` method of the `Element` type like this:
```Rust
.push(self.chart.view().map(FerrisMessage::Plot))
```

**Comment by bobgates** [comment]
Thanks. That's moved me on a lot, but I forgot to mention that I'd renamed Ferris and everything in it to TimePlot, so the structure looks like this:
```#[derive(Debug, Clone)]
pub enum TimePlotMessage {
    ImageWidthChanged(u16),
}```
It is referenced in ```update```:
```
    pub fn update(&mut self, message: TimePlotMessage) {
        match message {
            TimePlotMessage::ImageWidthChanged(value) => self.timeplot_width = value,
        }
    }
```
and then in ```fn content```, where the problem occurs. I think I'm using map wrong:
```
    fn content(&mut self) -> Element<'_, Self::Message> {
        let content = Column::new()
      . . .
            .push(self.chart.view().map(TimePlotMessage::ImageWidthChanged));
```
and the other step is here:
```
    fn view(&mut self) -> Element<Message> {
        let chart = ChartWidget::new(self)
            .width(Length::Fill)
            .height(Length::Fill);

        chart.into()
    }
```

I'm now getting an error about how a function is expected, but what is passed isn't a function. I'm still getting used to passing functions around, and to ```map```. Many thanks for your help so far, can you help further?

**Comment by Kaiden42** [comment]
> Thanks. That's moved me on a lot, but I forgot to mention that I'd renamed Ferris and everything in it to TimePlot, so the structure looks like this:

Than it might be the other side around. What type of message is the element producing, that is created by `self.chart.view()`? You have to make sure, that all the elements of the surrounding element (like the column in this example) are producing the same type of message.

```
fn view(&mut self) -> Element<Message> { ... }
```
Is this the method signature of your plot view? If so, than it produces the wrong kind of message. Your `TimePlotMessage` is part of `Message` but `Message` is not part of `TimePlotMessage`. Therefore you cant wrap a `Message` in a `TimePlotMessage` which is than wrapped again in a `Message`. (Well you could if the `TimePlotMessage` has a variant `Message::(Message)`, but this adds a nasty loop while processing the message and I wouldn't recommend this).

> and then in fn content, where the problem occurs. I think I'm using map wrong:

The map function takes an `Fn(A) -> B` as an argument. In other words, you have to provide a function that can map one kind of message to another one. This [line](https://github.com/iced-rs/iced_aw/blob/main/examples/tabs/src/ferris.rs#L64) of the example:
```Rust
content.map(Message::Ferris)
```
Is nothing else than a shorthand of the compiler and is equivalent to (see [here](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure)):
```Rust
content.map( |ferris_message| Message::Ferris(ferris_message) )
```
as the enum variant with unnamed fields can act like a function that creates the enum value.

**Comment by bobgates** [comment]
Thanks for that. I'm currently implementing what I want to see in a non-tabbed environment, and will get back to tabs once that's done. But your explanation has helped a lot.

**Comment by bobgates** [comment]
The mapping to appropriate messages helped. It is a lot to get my head around, but is working nicely now.
