### ISSUE TITLE
Tabs don't work with the latest cargo iced version?

### ISSUE THREAD

**Issue by matidfk** [iced-rs/iced_aw#65]
![image](https://user-images.githubusercontent.com/72168331/201550200-cdad84a0-555b-45b7-b0d1-1bafe693fa29.png)
keep getting errors like this, tried with all 3 different versions of Tabs in this repo

**Comment by matidfk** [comment]
here is the full error, this time when using iced_aw::native::Tabs:
```error[E0277]: the trait bound `iced_native::element::Element<'_, Message, iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend, Theme>>: From<iced_aw::native::Tabs<'_, Message, _>>` is not satisfied
  --> src/main.rs:81:9
   |
81 |         Tabs::new(self.index, Message::Switch).into()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---- required by a bound introduced by this call
   |         |
   |         the trait `From<iced_aw::native::Tabs<'_, Message, _>>` is not implemented for `iced_native::element::Element<'_, Message, iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend, Theme>>`
   |
   = help: the following other types implement trait `From<T>`:
             <iced_native::element::Element<'a, Message, Renderer> as From<&'a str>>
             <iced_native::element::Element<'a, Message, Renderer> as From<iced::widget::ProgressBar<Renderer>>>
             <iced_native::element::Element<'a, Message, Renderer> as From<iced::widget::Rule<Renderer>>>
             <iced_native::element::Element<'a, Message, Renderer> as From<iced::widget::Slider<'a, T, Message, Renderer>>>
             <iced_native::element::Element<'a, Message, Renderer> as From<iced::widget::Space>>
             <iced_native::element::Element<'a, Message, Renderer> as From<iced_native::overlay::menu::List<'a, T, Renderer>>>
             <iced_native::element::Element<'a, Message, Renderer> as From<iced_native::widget::button::Button<'a, Message, Renderer>>>
             <iced_native::element::Element<'a, Message, Renderer> as From<iced_native::widget::checkbox::Checkbox<'a, Message, Renderer>>>
           and 14 others
   = note: required for `iced_aw::native::Tabs<'_, Message, _>` to implement `Into<iced_native::element::Element<'_, Message, iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend, Theme>>>```

**Comment by Kaiden42** [comment]
What version of `iced` do you use?

**Comment by genusistimelord** [comment]
You will need to use iced 0.5.2 in order to use the master Repo. Otherwise these errors will occur if you are not. Master will not work with 0.4 please use the current crates.io version 0.2 for that. If you still get the issue after changing everything then please try to run cargo clean && cargo update. If you still get the error after that then please Release a small working snippet of the code failing to compile. 

Thank you
