### ISSUE TITLE
how to set floating_element example button become a round

### ISSUE THREAD

**Issue by Sherlock-Holo** [iced-rs/iced_aw#66]
at commit 81b4dd16a695d9c89c4338401bd88202e5dc2108 version, the floating_element example button is a rectangular, not a round
![image](https://user-images.githubusercontent.com/10096425/201596572-2bba4b79-1a58-40f0-b531-9b5fb46323d0.png)

**Comment by genusistimelord** [comment]
In order to make it round you must create your own Custom Theme and set a button style that gives back the roundness to the buttons style. We just did not do this since it can be a lot of work and not worth while in an example.

**Comment by Sherlock-Holo** [comment]
> In order to make it round you must create your own Custom Theme and set a button style that gives back the roundness to the buttons style. We just did not do this since it can be a lot of work and not worth while in an example.

I try the custom appearance and set the radius to 20.0 to make it look like a round, and it works.
i see the example gif and it's a round so i think i can follow the example to get the round button directly 😔

**Comment by genusistimelord** [comment]
if you wanted to submit a PR to turn it back round we would accept it. There was so much work to convert all of this to iced 0.5...

**Comment by Sherlock-Holo** [comment]
https://github.com/iced-rs/iced_aw/pull/67
I have created a PR, if you find any problems, please let me know:) @genusistimelord

**Comment by genusistimelord** [comment]
ok I have merged the PR so I will be closing this.
