### ISSUE TITLE
iced_aw theming

### ISSUE THREAD

**Issue by BKSalman** [iced-rs/iced_aw#75]
is it possible to theme and style widgets from iced_aw while using ``iced v0.5``/``iced v0.6``?

if so, how do I do it? couldn't figure it out on my own

I don't know where to track progress on that

**Comment by genusistimelord** [comment]
you will either need to use the preset Styles of Iced_aw like  https://github.com/iced-rs/iced_aw/blob/main/examples/card/src/main.rs#L49

OR use Ice's Theme styling to make your own Styles using something similar to this
https://github.com/iced-rs/iced_aw/blob/main/src/style/card.rs#L71

However for how to actually make a fully customized theme be better to reach out to Iced for a good example .

**Comment by BKSalman** [comment]
Alright, thanks for replying!

will close this issue :)
