### ISSUE TITLE
bug : Pick list is broken when using a FloatingElement

### ISSUE THREAD

**Issue by nicos68** [iced-rs/iced_aw#77]
When using FloatingElement in an application, pick lists do not display selectable values anymore.
I made a Minimal reproducible example [here](https://github.com/nicos68/iced_aw_floating_example).

**Comment by t18b219k** [comment]
This is same issue as  https://github.com/iced-rs/iced/issues/1591.

**Comment by genusistimelord** [comment]
this is a issue because he has to separate Overview from regular rendering.  Only way to truly fix this is for Iced to Adapt a better method of determining what is focused and what is not.

**Comment by greatest-ape** [comment]
https://github.com/iced-rs/iced/issues/1591 has been closed as having been fixed by https://github.com/iced-rs/iced/pull/1655. Will code in this repo have to be adjusted?

**Comment by genusistimelord** [comment]
not entirely sure yet on if any changes need to be made. Ill need to get with him to see.

**Comment by greatest-ape** [comment]
Ok! I forgot to mention that it’s still not working for me.

**Comment by genusistimelord** [comment]
yeah this library would need to be synced with the main repo in order for you to use it with the current iced repo. at least.

**Comment by greatest-ape** [comment]
It is unclear to me if the PR enables overlays on top of overlays or just having multiple overlays in general.

**Comment by greatest-ape** [comment]
See also https://github.com/iced-rs/iced/issues/940

**Comment by genusistimelord** [comment]
yeah until he can figure out how to get them to overlay correctly nothing will change.

**Comment by Kirottu** [comment]
This seems to still be broken with latest iced.

**Comment by genusistimelord** [comment]
it probably is fixable now since the newer iced offers a way to generate layers for overlays. just need to find time to do and test it.
