### ISSUE TITLE
Make DatePicker / TimePicker manage their open state themselves like PickList

### ISSUE THREAD

**Issue by big-lip-bob** [iced-rs/iced_aw#84]
I'd suggest making date_picker and time_picker widgets behave like a pick_list does, ie keep their opened and closed status themselves instead of having to generate events at all times, or at least have adapters that use a button in the back as a sane default ?
As in my case, its not trivial to track that given how much of them and where i'll have them in my dynamic layout.

**Comment by genusistimelord** [comment]
yeah Looking at the code the reason we did this was to allow you to use any clickable control to open them. Generally as ease of use this can be changed to a single button with text for simplicity.

**Comment by big-lip-bob** [comment]
Don't get me wrong, the current implementation is good for what it is, but just having a default backed by a button and a date formatter, either a closure or a string format from chrono if we're using it already. And if it would track its own closed / open status like the picklist does.

**Comment by genusistimelord** [comment]
So I had looked into this and due to the massive amount of changes to how they work that would be needed I decided it was best to not make these changes to them. So I will be closing this. If someone else would want to make the changes later feel free too.
