### ISSUE TITLE
Allow NumberInput to have the same value as its minimum and maximum

### ISSUE THREAD

**Issue by Redfire75369** [iced-rs/iced_aw#85]
`NumberInput::bounds()`, `NumberInput::max()` and `NumberInput::min()` all currently check that the minimum is less than the maximum. However, it would be nice if they checked if the minimum is less than or equal to the maximum. This would allow for a static number input with both the step buttons grayed out. A possible use case for this is a "locked" number input.

**Comment by genusistimelord** [comment]
I don't see any harm in adding this capability.  will look into it when I get some time.
