### ISSUE TITLE
Menu crash

### ISSUE THREAD

**Issue by t18b219k** [iced-rs/iced_aw#93]
I think I build menu correctly but sometimes crash .
every run generate random  index 1,10,7 or else and crash.

```
thread 'main' panicked at 'index out of bounds: the len is 10 but the index is 10', C:\Users\goldp\.cargo\git\checkouts\iced_aw-6122b81f7c90d3a2\2ef0a0a\src\native\menu\menu_inner.rs:413:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/iced-rs/iced_aw/blob/f2b1bbb743303ccac304e8c4e5f93336a7619628/src/native/menu/menu_inner.rs#L413

Environment
* iced_future runtime tokio
* gfx backend iced_wgpu on vulkan
* os Windows11 22H2
*  i use menubar in pane grid and multiple menubar to build icon button with dropdown menu.
*  menu contains Image and Text widget

**Comment by genusistimelord** [comment]
could you please give the code you used or build a minimal example of this occurring?

**Comment by t18b219k** [comment]
clone https://github.com/t18b219k/voice_vox_gui.git
first we need to install VoiceVox japanese TTS software to run this problematic code.

and cargo run.

**Comment by t18b219k** [comment]
I removed icon but still crash.

**Comment by latidoremi** [comment]
> clone https://github.com/t18b219k/voice_vox_gui.git first we need to install VoiceVox japanese TTS software to run this problematic code.
> 
> and cargo run.

Sorry I don't read Japanese but I played with the ui for a bit, none of the crashes came from iced_aw, where exactly should I be looking at?

**Comment by t18b219k** [comment]
modified menu_inner.rs to check mt.index is valid for menu no crash but sub menu not rendered.

**Comment by t18b219k** [comment]
modified to check mt.index is valid for menu crash reduced but still crash in on_event.

**Comment by t18b219k** [comment]
sub menu rendering crash + main menu scroll crash.

**Comment by latidoremi** [comment]
Ok I see where the problem is, the widget tree did not update when the menu tree changed on condition, a simple fix would be to recreate the widget tree in diff since the non linear children structure is a bit tricky to diff, dunno how much it'll affect the performance tho, I'll see if there's a better way

**Comment by t18b219k** [comment]
ok i'm happy to improve menu widget quality.

**Comment by latidoremi** [comment]
@t18b219k Checkout the code in the linked PR and see if it actually fixed the problem

**Comment by t18b219k** [comment]
Works fine.
oddly crash gone!

**Comment by genusistimelord** [comment]
I shall push that new change.
