### ISSUE TITLE
expected enum `Font`, found associated type

### ISSUE THREAD

**Issue by alex13sh** [iced-rs/iced_aw#98]
What is iced_native::Font used for in text::Render?
`Renderer: iced_native::text::Renderer<Font = iced_native::Font>,` 

In the iced widgets use just `Renderer: text::Renderer,`

**Comment by genusistimelord** [comment]
tbh I don't remember why we used it that way. Might do with supporting fonts outside of iced itself, Or it could simply be a older version of iced had more strict requirements and the newer iced does not.

**Comment by genusistimelord** [comment]
iced_native::text::Renderer<Font = iced_native::Font> is needed for us to be able to pull in and set the icon like 

`font: crate::graphics::icons::ICON_FONT,`

Without specifying this Iced will Error on that line.
